# Generated by Django 5.2.1 on 2025-05-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('avg_price', models.FloatField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
